[client]
toolbarMode = "viewer"
showErrorDetails = "none"

[theme]
base = "light"
primaryColor = "#295CFF"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#102033"
font = "sans serif"
