[auth]
redirect_uri = "https://exec-dash.streamlit.app/oauth2callback/"
cookie_secret = "<A_LONG_RANDOM_SECRET>"

[auth.auth0]
client_id = "<YOUR_CLIENT_ID>"
client_secret = "<YOUR_CLIENT_SECRET>"
server_metadata_url = "https://dev-oahowz1bcfj5r13o.us.auth0.com/.well-known/openid-configuration"

[database]
BOOF_API_KEY = "sk-fhgsadkjhfgasdjkhfgdasj9RsdA4u5d7iJKfXV7hkjhdfglkjghljksdfhg"
AIVEN_HOST = "coolition-platform-postgres-coolition-platform-001.k.aivencloud.com"
AIVEN_PORT = "15956"
AIVEN_USER = "cool_gpt"
AIVEN_PASSWORD = " ,nasdkljfghadsfljkghfadljkgh"
AIVEN_DB = "Cool_Impower"
NOOKIE_PASS = "LaTshlkjdfgsk;jlhsdfkljhgdf"

[api]
AGENT_API_URL="https://coolitionapiservice-1.onrender.com"

[python]
version = "3.14"

[elevenlabs]
api_key = "sk_blahblah"


[azure_devops]
organization = "YOUR_ADO_ORG"
pat = "YOUR_ORG_SCOPED_PAT"
api_version = "7.1"
